# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100)),
                ('output', models.TextField()),
                ('script', models.TextField()),
                ('execute_script', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'interaction',
            },
        ),
    ]
